var TB=YAHOO.namespace("TB");YAHOO.namespace("TB.app.Trade");
YAHOO.lang.augmentObject(TB.app.Trade,function(){var s=YAHOO.util,d=s.Dom,h=s.Event,j=TB.app.Trade;return{ListSelector:function(a){var b={checkCount:0,selectors:[],allSelectors:[],MAX_COUNT:0,ALL_COUNT:0,init:function(c){this.selectors=d.getElementsByClassName("selector","input",c);this.allSelectors=d.getElementsByClassName("all-selector","input",c);this.MAX_COUNT=this.selectors.length;this.ALL_COUNT=this.allSelectors.length;this.initAllSelectors();this.initSelectors()},initAllSelectors:function(){d.batch(this.allSelectors,
function(c){h.on(c,"click",function(){var e=this.checked;b.checkedCount=e?b.MAX_COUNT:0;for(var g=0;g<b.MAX_COUNT;++g)b.selectors[g].checked=e;for(g=0;g<b.ALL_COUNT;++g)b.allSelectors[g].checked=e})})},initSelectors:function(){d.batch(this.selectors,function(c){h.on(c,"click",function(){if(c.checked){b.checkedCount++;if(b.checkedCount==b.MAX_COUNT)for(e=0;e<b.ALL_COUNT;++e)b.allSelectors[e].checked=true}else{for(var e=0;e<b.ALL_COUNT;++e)b.allSelectors[e].checked=false;b.checkedCount--}})})}};b.init(a);
return b},DialogMgr:{currentDialog:null,currentTrigger:null,initTriggers:function(a){a=d.getElementsByClassName("J_DialogTrigger","*",a||document.body);for(var b=this,c=0,e=a.length;c<e;++c)h.on(a[c],"click",function(g){h.preventDefault(g);g=this.href;var f=j.Util.parseQueryString(this.getAttribute("data"));b.currentTrigger=this;j.DialogMgr.showDialog(g,f)})},initDialogCloseBtn:function(){h.on("J_ContainerClose","click",function(){parent.TB.app.Trade.DialogMgr.hideDialog()})},initDialog:function(a){a=
a||{};a.width=a.width||"690px";a.height=a.height||"280px";a.visible=a.visible||false;a.modal=a.modal!==false;a.draggable=a.draggable||false;a.close=a.close!==false;var b=d.get("J_Dialog");b=document.createElement("div");b.id="J_Dialog";d.addClass(b,"dialog");var c=document.createElement("iframe");c.name="dialogFrame";c.style.width=parseInt(a.width)-20+"px";c.style.height=parseInt(a.height)-20+"px";c.setAttribute("frameBorder","0");c.setAttribute("scrolling","no");c.src="about: blank";var e=document.createElement("div");
d.addClass(e,"bd");e.appendChild(c);b.appendChild(e);document.body.appendChild(b);document.body.appendChild(b);this.currentDialog=new YAHOO.widget.Panel(b,a);this.currentDialog.render();d.addClass(document.body,"yui-skin-sam");a=d.getElementsByClassName("container-close","a",b);if(a.length==1){a=a[0];h.purgeElement(a);h.on(a,"click",function(g){h.preventDefault(g);this.hideDialog()},this,true)}},showDialog:function(a,b){this.currentDialog||this.initDialog(b);if(a.indexOf("?")==-1)a+="?";a+="&t="+
(new Date).getTime();d.get("J_Dialog").getElementsByTagName("iframe")[0].src=a;this.currentDialog.center();this.currentDialog.show()},hideDialog:function(a){if(typeof a=="undefined")a=false;if(a)if(!confirm("\u786e\u8ba4\u5173\u95ed\u7a97\u53e3\u4e48\uff1f"))return false;d.get("J_Dialog").getElementsByTagName("iframe")[0].src="about:blank";this.currentDialog.hide();a=d.get("J_Dialog_c");var b=d.get("J_Dialog_mask"),c=d.get("_yuiResizeMonitor");a.parentNode.removeChild(a);b.parentNode.removeChild(b);c.parentNode.removeChild(c);this.currentDialog=
null}},TradeOperations:{ModifyPrice:function(a){function b(){var k=String(this.value),n=k.lastIndexOf(".");if(!(n<0||k.length<n+1)){var m=k.substring(n+1);if(m.length>2)this.value=k.substring(0,n)+"."+m.substring(0,2)}}function c(){for(var k=0,n=p.length;k<n;++k){var m=p[k],q=YAHOO.lang.trim(m.value);if(q==""){m.value="0";q=0}if(parseFloat(q)!=q){d.removeClass(l,"hidden");m.focus();return false}}k=YAHOO.lang.trim(r.value);if(parseFloat(k)<0){d.removeClass(l,"hidden");r.focus();return false}return true}
if(a=d.get(a)){var e=parseFloat(d.get("J_OriginalPrice").innerHTML),g=d.get("J_PostFee"),f=d.get("J_AdjustFee"),i=d.get("J_TotalPrice"),l=d.get("J_ErrorMsg"),o=a.elements.adjustFee,r=a.elements.postFee,v=!!a.elements.discount;if(v)var w=a.elements.discount.getAttribute("data-value");var p=[];o.length||(o=[o]);for(var t=0,x=o.length;t<x;++t)p.push(o[t]);p.push(r);h.on(p,"blur",function(){if(c())try{var k=parseFloat(r.value).toFixed(2);g.innerHTML=k;for(var n=0,m=0,q=o.length;m<q;++m){var y=YAHOO.lang.trim(o[m].value);
n+=parseFloat(y)}m="";m=n<0?"- "+Math.abs(n).toFixed(2):"+ "+Math.abs(n).toFixed(2);f.innerHTML=m;var u=parseFloat(e)+parseFloat(k)+parseFloat(n);if(v)u-=w;u<=0?d.removeClass(l,"hidden"):d.addClass(l,"hidden");i.innerHTML=u.toFixed(2)}catch(z){d.removeClass(l,"hidden")}});h.on(a,"submit",function(k){if(!d.hasClass(l,"hidden")){h.preventDefault(k);j.Util.twinkleErrorBox(l)}});h.on(p,"input",b);h.on(p,"propertychange",b)}},CancelOrder:function(a){(a=d.get(a))&&h.on(a,"submit",function(b){if(d.get("J_CloseReason").selectedIndex==
0){h.preventDefault(b);d.removeClass("J_ErrorMsg","hidden");j.Util.twinkleErrorBox("J_ErrorMsg")}})}},Util:{togglePanel:function(a,b,c){a=d.get(a);b=d.get(b);a&&b&&h.on(a,"click",function(e){h.preventDefault(e);b.style.display=b.style.display!="none"?"none":"block";c&&c(a,b)})},toggleOrderDetail:function(a){var b=d.getElementsByClassName("hidden-detail","tbody",a),c=0;for(a=b.length;c<a;++c)(function(){var e=b[c],g=d.getElementsByClassName("order-hd","tr",e);h.on(g,"click",function(f){f=h.getTarget(f).tagName;
f=="INPUT"||f=="A"||(d.hasClass(e,"hidden-detail")?d.replaceClass(e,"hidden-detail","display-detail"):d.replaceClass(e,"display-detail","hidden-detail"))})})()},initUserInfoPopup:function(a){if(a&&a.getAttribute("data")){var b=a.getElementsByTagName("img");b&&b.length>0&&b[0].setAttribute("alt","");var c=document.createElement("div");d.addClass(c,"popup-info-box");b='<div class="bl"><div class="br">';b+='<div class="bd user-info">';b+="\u6b63\u5728\u52a0\u8f7d\u2026\u2026";b+="</div>";b+="</div></div>";b+='<div class="bt"><div class="corner bt-l"></div><div class="mid"></div><div class="corner bt-r"></div></div>';
c.innerHTML=b;document.body.appendChild(c);TB.widget.SimplePopup.decorate(a,c,{offset:[0,-10],position:"right",effect:"fade",disableClick:false,onShow:function(){d.setStyle(c,"display","block");if(!(c.getElementsByTagName("h5").length>0)){var e=d.getElementsByClassName("user-info","div",c)[0],g=a.getAttribute("data");YAHOO.util.Connect.asyncRequest("GET",g,{success:function(f){try{var i=eval("("+f.responseText+")");f="<h5>\u8054\u7cfb\u4fe1\u606f</h5>";f+='<table class="user-info-table"><tbody>';f+="<tr><th>\u59d3\u540d\uff1a</th><td>"+
i.name+"</td></tr>";f+="<tr><th>\u7535\u8bdd\uff1a</th><td>"+i.tel+"</td></tr>";f+="<tr><th>\u624b\u673a\uff1a</th><td>"+i.mobile+"</td></tr>";f+="<tr><th>\u5907\u7528\u7535\u8bdd\uff1a</th><td>"+i.otherPhone+"</td></tr>";f+="<tr><th>\u7535\u5b50\u90ae\u4ef6\uff1a</th><td>"+i.email+"</td></tr>";f+="<tr><th>\u57ce\u5e02\uff1a</th><td>"+i.city+"</td></tr>";f+='<tr class="sep"><td colspan="2"><hr></td></tr>';if(i.message){f+='<tr><th>\u4e70\u5bb6\u7559\u8a00\uff1a</th><td class="message">'+i.message+"</td></tr>";f+='<tr class="sep"><td colspan="2"><hr></td></tr>'}var l="";if(i.attachInfo)for(key in i.attachInfo)l+="<tr><th>"+
key+"\uff1a</th><td>"+i.attachInfo[key]+"</td></tr>";if(l.length>0)f+=l;f+="</tbody></table>";l="";if(i.buyerAddress&&i.buyerAddress.length>0)l+='<a href="'+i.buyerAddress+'" target="_blank">\u67e5\u770b\u6536\u8d27\u5730\u5740</a>';if(l.length>0)f+='<div class="view-address">'+l+"</div>";e.innerHTML=f}catch(o){e.innerHTML="\u5bf9\u4e0d\u8d77\uff0c\u6682\u65f6\u65e0\u6cd5\u83b7\u5f97\u6570\u636e\uff0c\u8bf7\u7a0d\u5019\u91cd\u8bd5\u3002"}},failure:function(){e.innerHTML="\u5bf9\u4e0d\u8d77\uff0c\u6682\u65f6\u65e0\u6cd5\u83b7\u5f97\u6570\u636e\uff0c\u8bf7\u7a0d\u5019\u91cd\u8bd5\u3002"}})}}})}},initXBCardPopup:function(){var a=document.createElement("div");a.id="XBCardPopup";a.setAttribute("style","background: #fff;width: 602px; display: none; z-index: 999999");
a.innerHTML='<iframe id="XBCardFrame" src="about:blank" width="602" height="302" frameborder="0" scrolling="no"></iframe>';document.body.appendChild(a);var b=d.getElementsByClassName("J_XBCard","a","J_ListTable");TB.widget.SimplePopup.decorate(b,a.id,{width:602,height:402,position:"bottom",eventType:"click",offset:[-500,-100],onShow:function(){d.get("XBCardFrame").src=this.trigger.href}})},twinkleErrorBox:function(a,b){var c=d.get(a);if(c=d.getFirstChild(c)){b=b||2;var e=true,g=YAHOO.lang.later(200,
null,function(){d.setStyle(c,"borderWidth",e?"0":"1px");e=!e},null,true);YAHOO.lang.later(b*1E3,null,function(){d.setStyle(c,"borderWidth","1px");g.cancel()})}},parseQueryString:function(a,b,c){if(!a||!a.length)return{};var e={};a=a.split(c||"&");for(var g,f=0,i=a.length;f<i;++f){g=a[f].split("=");c=decodeURIComponent(g[0]);g=decodeURIComponent(g[1]);if(g===""||g==="undefined")g=undefined;if(b===true)e[c]=g;else if(typeof e[c]=="undefined")e[c]=g;else{if(typeof e[c]=="string")e[c]=[e[c]];e[c].push(g)}}return e}},
PageInit:function(a){function b(){j.Util.togglePanel("J_SearchBoxToggle","J_SearchBox",function(f){d.hasClass(f,"collapsed-tool-toggle")?d.removeClass(f,"collapsed-tool-toggle"):d.addClass(f,"collapsed-tool-toggle")})}function c(){j.Util.togglePanel("J_RefundHelpBoxToggle","J_RefundHelpBox",function(f){f=f.parentNode;d.hasClass(f,"collapsed")?d.removeClass(f,"collapsed"):d.addClass(f,"collapsed")})}if(a=="list-sold-items"||a=="list-bought-items"){b();new j.ListSelector("J_ListTable");j.Util.toggleOrderDetail("J_ListTable");
d.getElementsByClassName("J_UserInfo","span","J_ListTable",function(f){j.Util.initUserInfoPopup(f)})}a=="list-bought-items"&&j.Util.initXBCardPopup();if(a=="list-sold-items"){j.Util.togglePanel("J_BatchExportBtn","J_BatchExportPanel");j.Util.togglePanel("J_BatchExportPanelCloseBtn","J_BatchExportPanel")}if(a=="trade-order-detail"){var e=TB.widget.SimpleTab.decorate("J_TabView",{eventType:"mouse",currentClass:"current",tabPanelClass:"info-box"}),g=location.hash;if(g&&g.length==5){g=g.substring(4);
e.switchTab(g)}}if(a=="list-sold-items"||a=="list-bought-items"||a=="trade-order-detail"){if(d.getElementsByClassName("J_DialogTrigger","*",document.body).length==0)return;(new s.YUILoader({require:["container"],base:"http://assets.taobaocdn.com/yui/2.6.0/build/",onSuccess:function(){j.DialogMgr.initTriggers()},onFailure:function(f){alert("error: "+YAHOO.lang.dump(f))}})).insert()}a=="modify-price"&&j.TradeOperations.ModifyPrice(document.forms.modifyPriceForm);a=="cancel-order"&&j.TradeOperations.CancelOrder(document.forms.cancelOrderForm);
if(a=="modify-price"||a=="cancel-order"||a=="delay-trade"||a=="batch-pay")j.DialogMgr.initDialogCloseBtn();a=="my-point"&&b();a=="refund-list"&&c()}}}());
